- name: Create namespace
  hosts: localhost
  gather_facts: no
  vars_files:
  - vars/three-stends.yaml
  tasks:
    - name: Create namespace with tag
      k8s:
        kubeconfig: "{{ kubeconfig_file }}"
        state: present
        definition:
          apiVersion: v1
          kind: Namespace
          metadata:
            name: "{{ namespace }}"
            labels:
              notdelete: "true"
      when: not_delete == "true"

    - name: Create namespace
      k8s:
        kubeconfig: "{{ kubeconfig_file }}"
        state: present
        definition:
          apiVersion: v1
          kind: Namespace
          metadata:
            name: "{{ namespace }}"
      when: not_delete == "false"

- name: Deploy warp and px-profi
  hosts: localhost
  gather_facts: no
  roles:
  - deploy_registry_cred
  - deploy_warp
  - deploy_px
  - deploy_seo
  - deploy_system
  vars_files:
  - vars/three-stends.yaml