- name: Deploy env configmap
  k8s_raw:
    kubeconfig: "{{ kubeconfig_file }}"
    state: present
    definition: "{{ lookup('template', '{{ role_path }}/templates/env-configmap.yaml') | from_yaml }}"

- name: Deploy nginx configmap
  k8s_raw:
    kubeconfig: "{{ kubeconfig_file }}"
    state: present
    definition: "{{ lookup('template', '{{ role_path }}/templates/nginx-configmap.yaml') | from_yaml }}"

- name: Deploy deployment
  k8s_raw:
    kubeconfig: "{{ kubeconfig_file }}"
    state: present
    definition: "{{ lookup('template', '{{ role_path }}/templates/deployment.yaml') | from_yaml }}"

- name: Deploy service
  k8s_raw:
    kubeconfig: "{{ kubeconfig_file }}"
    state: present
    definition: "{{ lookup('template', '{{ role_path }}/templates/service.yaml') | from_yaml }}"

- name: Deploy ingress
  k8s_raw:
    kubeconfig: "{{ kubeconfig_file }}"
    state: present
    definition: "{{ lookup('template', '{{ role_path }}/templates/ingress.yaml') | from_yaml }}"
